<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
	<head>
		<meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
		<title>Kumbia Amecasoft (Jquery/Ajax)</title>
		<link rel="shortcut icon" href="<?= PUBLIC_PATH ?>favicon.ico" type="image/x-icon" /> 
		
		<?= stylesheet_link_tag('style') ?>
		
		<?= View::partial("jquery",false,'template: ui-darkness'); ?>
        
        <?= javascript_include_tag('kumbia/validations') ?>
		<?= javascript_include_tag('amecasoft') ?>
        
	</head>
	<body>
		<?php View::content(); ?>
	</body>
</html>