<?php if(!isset($template)) $template = "ui-darkness" ?>

<?= stylesheet_link_tag('jquery/'.$template.'/jquery-ui-1.8.13.custom') ?> 

<?= javascript_include_tag('jquery/jquery-1.4.2.min')."\n" ?>
<?= javascript_include_tag('jquery/jquery-ui-1.8.13.custom.min')."\n" ?>
<?= javascript_include_tag('jquery/jquery.form')."\n" ?>
<?= javascript_include_tag('jquery/jquery.metadata')."\n" ?>
<?= javascript_include_tag('jquery/jquery.validate')."\n" ?>
<?= javascript_include_tag('jquery/kumbia_jquery') ?>