<style type="text/css">
    body{
        background-color: #000000;
    }
</style>
<div style="text-align: center; margin: 50px; font-size: 12pt; font-family: Lucida Grande, Verdana, Sans-serif;">
	<table align="center" id="content" style="padding: 10px 10px 6px 10px; width: 50%;">
		<tbody>
			<tr>
				<td>
					<img src="<?php echo PUBLIC_PATH ?>img/amecamx.png" width="500" />
				</td>
				<td>
					<h1 style="font-size: 18pt; color: #285375; margin: 0 0 4px 0;">Página No Encontrada</h1>
					<br />
					<a href="http://ameca.mx/" style="font-size: 14pt; color: #285375; margin: 0 0 4px 0; text-decoration: none;">Ir a la pagina de Inicio de Ameca.Mx</a>
				</td>
			</tr>
		</tbody>
	</table>
</div>